name: MyFirstModule
main: com.github.gabrielos.main.Main
version: 0.0.0.0.0.0.0.1
api-version: 1.15
commands:
   create:
      description: Your description
      usage: /<command>
   dead:
      description: Your description
      usage: /<command>